[project]
name = "sphinx-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = [
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
]
